#pragma once

enum GameState {
    GAME_LAUNCH_FADE_IN,
    MENU,
    CHANGE_MENU_TYPE_TO_MAIN,
    CHANGE_MENU_TYPE_TO_PAUSE,
    MENU_TO_GAME_FADE_OUT,
    NEW_GAME_SETUP,
    GAME_FADE_IN,
    GAME,
    DEATH_RESULTS,
    RESULTS_TO_GAME_FADE_OUT,
    GAME_EXIT_FADE_OUT
};
